'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const E=require('../crates/dir-simulator/src/tool/viewer/assets/ethernet-model.js');
const record=(schema,id,subject,frame,time,data)=>({schema_name:`ethernet.${schema}`,schema_version:1,record_id:id,subject,request_id:frame,origin_request_id:null,time_ps:String(time),data});
function fixture(){
 const frame=record('frame','g:0','N.a','g:0',0,{source:'N.a',src_mac:'02:00:00:00:00:01',dst_mac:'02:00:00:00:00:02',ether_type:'2048',data_hex:'',pad_bytes:'46',mac_bytes:'64',fcs_hex:'00000000',mac_hex:'00'.repeat(64),generated_ps:'0',ready_ps:'0'});
 const transfer=record('transfer','g:0@N.a.tx','N.a.tx','g:0',672000,{frame_id:'g:0',parent_transfer_id:null,from_port:'N.a.tx',to_port:'N.b.rx',queued_ps:'0',sof_ps:'0',eof_ps:'576000',release_ps:'672000',arrival_ps:'577000',planned_eof_ps:'576000',planned_release_ps:'672000',planned_arrival_ps:'577000',status:'serialized',drop_reason:null});
 const reception=record('reception','g:0@N.a.tx@rx','N.b','g:0',578000,{frame_id:'g:0',transfer_id:'g:0@N.a.tx',ingress:'N.b.rx',observed_ps:'577000',ready_ps:'578000',planned_ready_ps:'578000',status:'received',reason:null,egress_transfer_ids:[]});
 return {schema_version:2,metadata:{model_profile:'ethernet.l2.store-forward.v1',ethernet_topology:{devices:['a','b','quiet'].map(id=>({id:`N.${id}`,kind:'endpoint',mac:'02:00:00:00:00:01',queue_capacity:'4'})),directions:[{from_port:'N.a.tx',to_port:'N.b.rx',bitrate_bps:'1000000000',delay_ps:'1000'},{from_port:'N.b.tx',to_port:'N.a.rx',bitrate_bps:'1000000000',delay_ps:'1000'}]}},simulation:{start_ps:'0',end_ps:'1000000',partial:false,termination:'events_exhausted',model_records:[frame,transfer,reception]}};
}
test('milestones preserve independent serialization, arrival, release and receive boundaries',()=>{
 const m=E.parseResults(fixture());assert.equal(m.devices.size,3);assert.equal(E.stateAt(m,0n).counts.transmitting,1);assert.equal(E.stateAt(m,576000n).counts.serialized,1);assert.equal(E.stateAt(m,576000n).counts.received,0);assert.equal(E.stateAt(m,577000n).counts.processing,1);assert.equal(E.stateAt(m,578000n).counts.received,1);assert.equal(E.stateAt(m,0n).queues.get('N.b.tx').length,0);
});
test('partial run never invents reception from planned arrival',()=>{const raw=fixture(),t=raw.simulation.model_records[1];raw.simulation.end_ps='577000';raw.simulation.termination='time_limit';t.data.arrival_ps=null;t.data.release_ps=null;t.time_ps='576000';raw.simulation.model_records.pop();const m=E.parseResults(raw);assert.equal(m.receptions.size,0);assert.equal(E.stateAt(m,m.end).counts.received,0);assert.equal(E.stepTransfers(m,576000n)[0].arrived,false);assert.equal(E.stepTransfers(m,m.end).length,1,'pending propagation remains visible after committed EOF');assert.equal(E.stepTransfers(m,m.end)[0].arrived,false);});
test('capacity drop is retained without physical transfer',()=>{const raw=fixture(),t=raw.simulation.model_records[1];Object.assign(t.data,{status:'dropped',drop_reason:'queue_full',sof_ps:null,eof_ps:null,release_ps:null,arrival_ps:null,planned_eof_ps:null,planned_release_ps:null,planned_arrival_ps:null});t.time_ps='0';raw.simulation.model_records.pop();const m=E.parseResults(raw);assert.equal(E.stateAt(m,0n).counts.dropped,1);assert.deepEqual(E.stepTransfers(m,m.end),[]);});
test('replay at a destination is independent of navigation history',()=>{const m=E.parseResults(fixture());const expected=E.stepTransfers(m,577000n);E.stateAt(m,m.end);E.stepTransfers(m,578000n);assert.deepEqual(E.stepTransfers(m,577000n),expected);assert.equal(expected[0].from,'N.a.tx');assert.equal(expected[0].arrived,true);});
test('corrupt references, time order, envelope updates and fabricated receipts are rejected',()=>{for(const mutate of [r=>r.simulation.model_records[1].data.frame_id='missing',r=>r.simulation.model_records[1].data.planned_release_ps='1',r=>r.simulation.model_records[2].data.observed_ps='576999',r=>r.simulation.model_records[1].time_ps='1',r=>r.simulation.model_records[1].data.arrival_ps=null,r=>r.simulation.model_records[1].data.parent_transfer_id='g:0@N.a.tx']){const raw=fixture();mutate(raw);assert.throws(()=>E.parseResults(raw),/Ethernet:/);}});
test('large timestamps preserve picoseconds beyond binary64 safe integers',()=>{const raw=fixture(),offset=9007199254740993n;raw.simulation.end_ps=String(offset+1000000n);for(const r of raw.simulation.model_records){r.time_ps=String(BigInt(r.time_ps)+offset);for(const [k,v]of Object.entries(r.data))if(k.endsWith('_ps')&&v!==null)r.data[k]=String(BigInt(v)+offset);}const m=E.parseResults(raw);assert.equal(m.frames.get('g:0').generated_ps,offset);assert.equal(E.stateAt(m,offset-1n).counts.generated,0);assert.equal(E.stateAt(m,offset).counts.generated,1);});
module.exports={fixture};
test('opposite link directions transmit concurrently without sharing a queue',()=>{const raw=fixture();const reverse=JSON.parse(JSON.stringify(raw.simulation.model_records));for(const r of reverse){const swap=s=>s.replaceAll('N.a','N.TEMP').replaceAll('N.b','N.a').replaceAll('N.TEMP','N.b').replaceAll('g:0','h:0');for(const k of ['record_id','subject','request_id'])r[k]=swap(r[k]);for(const [k,v]of Object.entries(r.data))if(typeof v==='string')r.data[k]=swap(v);}raw.simulation.model_records.push(...reverse);const m=E.parseResults(raw);assert.equal(E.stateAt(m,0n).counts.transmitting,2);assert.equal(E.stateAt(m,578000n).counts.received,2);});
test('switch flood links accepted and dropped children to a single reception',()=>{const raw=fixture(),[frame,incoming,rx]=raw.simulation.model_records;raw.simulation.end_ps='2000000';raw.metadata.ethernet_topology.devices.find(d=>d.id==='N.b').kind='switch';
 Object.assign(rx.data,{status:'forwarded',egress_transfer_ids:['g:0@N.b.tx_c','g:0@N.b.tx_d']});
 raw.metadata.ethernet_topology.devices.push({id:'N.c',kind:'endpoint',mac:'02:00:00:00:00:03',queue_capacity:'4'},{id:'N.d',kind:'endpoint',mac:'02:00:00:00:00:04',queue_capacity:'4'});
 for(const target of ['c','d'])raw.metadata.ethernet_topology.directions.push({from_port:`N.b.tx_${target}`,to_port:`N.${target}.rx`,bitrate_bps:'1000000000',delay_ps:'1000'});
 const child=JSON.parse(JSON.stringify(incoming));child.record_id='g:0@N.b.tx_c';child.subject='N.b.tx_c';child.time_ps='1250000';Object.assign(child.data,{parent_transfer_id:incoming.record_id,from_port:'N.b.tx_c',to_port:'N.c.rx',queued_ps:'578000',sof_ps:'578000',eof_ps:'1154000',release_ps:'1250000',arrival_ps:'1155000',planned_eof_ps:'1154000',planned_release_ps:'1250000',planned_arrival_ps:'1155000'});
 const drop=JSON.parse(JSON.stringify(child));drop.record_id='g:0@N.b.tx_d';drop.subject='N.b.tx_d';drop.time_ps='578000';Object.assign(drop.data,{from_port:'N.b.tx_d',to_port:'N.d.rx',status:'dropped',drop_reason:'queue_full',sof_ps:null,eof_ps:null,release_ps:null,arrival_ps:null,planned_eof_ps:null,planned_release_ps:null,planned_arrival_ps:null});
 const received=record('reception',`${child.record_id}@rx`,'N.c','g:0',1155000,{frame_id:'g:0',transfer_id:child.record_id,ingress:'N.c.rx',observed_ps:'1155000',ready_ps:'1155000',planned_ready_ps:'1155000',status:'received',reason:null,egress_transfer_ids:[]});
 raw.simulation.model_records.push(child,drop,received);const m=E.parseResults(raw),state=E.stateAt(m,m.end);assert.equal(state.counts.generated,1);assert.equal(state.counts.serialized,2);assert.equal(state.counts.dropped,1);assert.equal(state.counts.forwarded,1);assert.equal(state.counts.received,1);assert.equal(m.receptions.size,2);
});
function qosFixture(){const raw=fixture();raw.metadata.model_profile='ethernet.l2.qos.v1';raw.metadata.ethernet_topology.outputs=raw.metadata.ethernet_topology.directions.map(d=>({port:d.from_port,scheduler:'strict_priority',queues:Array.from({length:8},(_,priority)=>({priority:String(priority),capacity_frames:'4',capacity_bytes:priority===7?'128':null}))}));const [f,t]=raw.simulation.model_records;f.schema_version=2;t.schema_version=2;Object.assign(f.data,{flow_id:'control',priority:'7',deadline_ps:'1000000',ready_ps:'10'});f.time_ps='10';Object.assign(t.data,{queue_id:'N.a.tx.queue.7',priority:'7',queued_ps:'10',sof_ps:'20'});return raw;}
test('QoS class queue occupancy counts MAC bytes and excludes active transfer',()=>{const m=E.parseResults(qosFixture());assert.equal(m.qos,true);assert.equal(m.frames.get('g:0').deadline_ps,1000000n);const q=E.stateAt(m,10n).classes.get('N.a.tx.queue.7');assert.equal(q.bytes,64n);assert.deepEqual(q.ids,['g:0@N.a.tx']);assert.equal(E.stateAt(m,20n).classes.get('N.a.tx.queue.7').bytes,0n);assert.equal(E.stateAt(m,20n).counts.transmitting,1);});
test('QoS schema is explicit: version mismatches, invalid class and incomplete topology reject',()=>{for(const mutate of [r=>r.metadata.model_profile='ethernet.l2.store-forward.v1',r=>r.simulation.model_records[0].schema_version=1,r=>r.simulation.model_records[1].data.priority='6',r=>r.simulation.model_records[1].data.queue_id='N.a.tx.queue.6',r=>r.metadata.ethernet_topology.outputs.pop(),r=>r.simulation.model_records[0].data.deadline_ps='-1']){const raw=qosFixture();mutate(raw);assert.throws(()=>E.parseResults(raw),/Ethernet:/);}});
