'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const E=require('../crates/dir-simulator/src/tool/viewer/assets/ethernet-model.js');
const record=(schema,id,subject,frame,time,data)=>({schema_name:`ethernet.${schema}`,schema_version:1,record_id:id,subject,request_id:frame,origin_request_id:null,time_ps:String(time),data});
function fixture(){
 const frame=record('frame','g:0','N.a','g:0',0,{source:'N.a',src_mac:'02:00:00:00:00:01',dst_mac:'02:00:00:00:00:02',ether_type:'2048',data_hex:'',pad_bytes:'46',mac_bytes:'64',fcs_hex:'00000000',mac_hex:'00'.repeat(64),generated_ps:'0',ready_ps:'0'});
 const transfer=record('transfer','g:0@N.a.tx','N.a.tx','g:0',672000,{frame_id:'g:0',parent_transfer_id:null,from_port:'N.a.tx',to_port:'N.b.rx',queued_ps:'0',sof_ps:'0',eof_ps:'576000',release_ps:'672000',arrival_ps:'577000',planned_eof_ps:'576000',planned_release_ps:'672000',planned_arrival_ps:'577000',status:'serialized',drop_reason:null});
 const reception=record('reception','g:0@N.a.tx@rx','N.b','g:0',578000,{frame_id:'g:0',transfer_id:'g:0@N.a.tx',ingress:'N.b.rx',observed_ps:'577000',ready_ps:'578000',planned_ready_ps:'578000',status:'received',reason:null,egress_transfer_ids:[]});
 return {schema_version:2,metadata:{model_profile:'ethernet.l2.store-forward.v1',ethernet_topology:{devices:['a','b','quiet'].map(id=>({id:`N.${id}`,kind:'endpoint',mac:'02:00:00:00:00:01',queue_capacity:'4'})),directions:[{from_port:'N.a.tx',to_port:'N.b.rx',bitrate_bps:'1000000000',delay_ps:'1000'},{from_port:'N.b.tx',to_port:'N.a.rx',bitrate_bps:'1000000000',delay_ps:'1000'}]}},simulation:{start_ps:'0',end_ps:'1000000',partial:false,termination:'events_exhausted',model_records:[frame,transfer,reception]}};
}
test('milestones preserve independent serialization, arrival, release and receive boundaries',()=>{
 const m=E.parseResults(fixture());assert.equal(m.devices.size,3);assert.equal(E.stateAt(m,0n).counts.transmitting,1);assert.equal(E.stateAt(m,576000n).counts.serialized,1);assert.equal(E.stateAt(m,576000n).counts.received,0);assert.equal(E.stateAt(m,577000n).counts.processing,1);assert.equal(E.stateAt(m,578000n).counts.received,1);assert.equal(E.stateAt(m,0n).queues.get('N.b.tx').length,0);
});
test('partial run never invents reception from planned arrival',()=>{const raw=fixture(),t=raw.simulation.model_records[1];raw.simulation.end_ps='577000';raw.simulation.termination='time_limit';t.data.arrival_ps=null;t.data.release_ps=null;t.time_ps='576000';raw.simulation.model_records.pop();const m=E.parseResults(raw);assert.equal(m.receptions.size,0);assert.equal(E.stateAt(m,m.end).counts.received,0);assert.equal(E.stepTransfers(m,576000n)[0].arrived,false);assert.equal(E.stepTransfers(m,m.end).length,1,'pending propagation remains visible after committed EOF');assert.equal(E.stepTransfers(m,m.end)[0].arrived,false);});
test('capacity drop is retained without physical transfer',()=>{const raw=fixture(),t=raw.simulation.model_records[1];Object.assign(t.data,{status:'dropped',drop_reason:'queue_full',sof_ps:null,eof_ps:null,release_ps:null,arrival_ps:null,planned_eof_ps:null,planned_release_ps:null,planned_arrival_ps:null});t.time_ps='0';raw.simulation.model_records.pop();const m=E.parseResults(raw);assert.equal(E.stateAt(m,0n).counts.dropped,1);assert.deepEqual(E.stepTransfers(m,m.end),[]);});
test('replay at a destination is independent of navigation history',()=>{const m=E.parseResults(fixture());const expected=E.stepTransfers(m,577000n);E.stateAt(m,m.end);E.stepTransfers(m,578000n);assert.deepEqual(E.stepTransfers(m,577000n),expected);assert.equal(expected[0].from,'N.a.tx');assert.equal(expected[0].arrived,true);});
test('corrupt references, time order, envelope updates and fabricated receipts are rejected',()=>{for(const mutate of [r=>r.simulation.model_records[1].data.frame_id='missing',r=>r.simulation.model_records[1].data.planned_release_ps='1',r=>r.simulation.model_records[2].data.observed_ps='576999',r=>r.simulation.model_records[1].time_ps='1',r=>r.simulation.model_records[1].data.arrival_ps=null,r=>r.simulation.model_records[1].data.parent_transfer_id='g:0@N.a.tx']){const raw=fixture();mutate(raw);assert.throws(()=>E.parseResults(raw),/Ethernet:/);}});
test('large timestamps preserve picoseconds beyond binary64 safe integers',()=>{const raw=fixture(),offset=9007199254740993n;raw.simulation.end_ps=String(offset+1000000n);for(const r of raw.simulation.model_records){r.time_ps=String(BigInt(r.time_ps)+offset);for(const [k,v]of Object.entries(r.data))if(k.endsWith('_ps')&&v!==null)r.data[k]=String(BigInt(v)+offset);}const m=E.parseResults(raw);assert.equal(m.frames.get('g:0').generated_ps,offset);assert.equal(E.stateAt(m,offset-1n).counts.generated,0);assert.equal(E.stateAt(m,offset).counts.generated,1);});
module.exports={fixture};
test('opposite link directions transmit concurrently without sharing a queue',()=>{const raw=fixture();const reverse=JSON.parse(JSON.stringify(raw.simulation.model_records));for(const r of reverse){const swap=s=>s.replaceAll('N.a','N.TEMP').replaceAll('N.b','N.a').replaceAll('N.TEMP','N.b').replaceAll('g:0','h:0');for(const k of ['record_id','subject','request_id'])r[k]=swap(r[k]);for(const [k,v]of Object.entries(r.data))if(typeof v==='string')r.data[k]=swap(v);}raw.simulation.model_records.push(...reverse);const m=E.parseResults(raw);assert.equal(E.stateAt(m,0n).counts.transmitting,2);assert.equal(E.stateAt(m,578000n).counts.received,2);});
test('switch flood links accepted and dropped children to a single reception',()=>{const raw=fixture(),[frame,incoming,rx]=raw.simulation.model_records;raw.simulation.end_ps='2000000';raw.metadata.ethernet_topology.devices.find(d=>d.id==='N.b').kind='switch';
 Object.assign(rx.data,{status:'forwarded',egress_transfer_ids:['g:0@N.b.tx_c','g:0@N.b.tx_d']});
 raw.metadata.ethernet_topology.devices.push({id:'N.c',kind:'endpoint',mac:'02:00:00:00:00:03',queue_capacity:'4'},{id:'N.d',kind:'endpoint',mac:'02:00:00:00:00:04',queue_capacity:'4'});
 for(const target of ['c','d'])raw.metadata.ethernet_topology.directions.push({from_port:`N.b.tx_${target}`,to_port:`N.${target}.rx`,bitrate_bps:'1000000000',delay_ps:'1000'});
 const child=JSON.parse(JSON.stringify(incoming));child.record_id='g:0@N.b.tx_c';child.subject='N.b.tx_c';child.time_ps='1250000';Object.assign(child.data,{parent_transfer_id:incoming.record_id,from_port:'N.b.tx_c',to_port:'N.c.rx',queued_ps:'578000',sof_ps:'578000',eof_ps:'1154000',release_ps:'1250000',arrival_ps:'1155000',planned_eof_ps:'1154000',planned_release_ps:'1250000',planned_arrival_ps:'1155000'});
 const drop=JSON.parse(JSON.stringify(child));drop.record_id='g:0@N.b.tx_d';drop.subject='N.b.tx_d';drop.time_ps='578000';Object.assign(drop.data,{from_port:'N.b.tx_d',to_port:'N.d.rx',status:'dropped',drop_reason:'queue_full',sof_ps:null,eof_ps:null,release_ps:null,arrival_ps:null,planned_eof_ps:null,planned_release_ps:null,planned_arrival_ps:null});
 const received=record('reception',`${child.record_id}@rx`,'N.c','g:0',1155000,{frame_id:'g:0',transfer_id:child.record_id,ingress:'N.c.rx',observed_ps:'1155000',ready_ps:'1155000',planned_ready_ps:'1155000',status:'received',reason:null,egress_transfer_ids:[]});
 raw.simulation.model_records.push(child,drop,received);const m=E.parseResults(raw),state=E.stateAt(m,m.end);assert.equal(state.counts.generated,1);assert.equal(state.counts.serialized,2);assert.equal(state.counts.dropped,1);assert.equal(state.counts.forwarded,1);assert.equal(state.counts.received,1);assert.equal(m.receptions.size,2);
});
function qosFixture(){const raw=fixture();raw.metadata.model_profile='ethernet.l2.qos.v1';raw.metadata.ethernet_topology.outputs=raw.metadata.ethernet_topology.directions.map(d=>({port:d.from_port,scheduler:'strict_priority',queues:Array.from({length:8},(_,priority)=>({priority:String(priority),capacity_frames:'4',capacity_bytes:priority===7?'128':null}))}));const [f,t]=raw.simulation.model_records;f.schema_version=2;t.schema_version=2;Object.assign(f.data,{flow_id:'control',priority:'7',deadline_ps:'1000000',ready_ps:'10'});f.time_ps='10';Object.assign(t.data,{queue_id:'N.a.tx.queue.7',priority:'7',queued_ps:'10',sof_ps:'20'});return raw;}
test('QoS class queue occupancy counts MAC bytes and excludes active transfer',()=>{const m=E.parseResults(qosFixture());assert.equal(m.qos,true);assert.equal(m.frames.get('g:0').deadline_ps,1000000n);const q=E.stateAt(m,10n).classes.get('N.a.tx.queue.7');assert.equal(q.bytes,64n);assert.deepEqual(q.ids,['g:0@N.a.tx']);assert.equal(E.stateAt(m,20n).classes.get('N.a.tx.queue.7').bytes,0n);assert.equal(E.stateAt(m,20n).counts.transmitting,1);});
test('QoS schema is explicit: version mismatches, invalid class and incomplete topology reject',()=>{for(const mutate of [r=>r.metadata.model_profile='ethernet.l2.store-forward.v1',r=>r.simulation.model_records[0].schema_version=1,r=>r.simulation.model_records[1].data.priority='6',r=>r.simulation.model_records[1].data.queue_id='N.a.tx.queue.6',r=>r.metadata.ethernet_topology.outputs.pop(),r=>r.simulation.model_records[0].data.deadline_ps='-1']){const raw=qosFixture();mutate(raw);assert.throws(()=>E.parseResults(raw),/Ethernet:/);}});
// Published wire vectors are independent of the viewer codec (known header and FCS).
const vlanVectors=require('../docs/verification/fixtures/ethernet-vlan/wire-vectors.json').vectors;
function vectorWire(tagged){const v=vlanVectors[tagged?1:0],e=v.expected;return {src_mac:v.input.src_mac,dst_mac:v.input.dst_mac,ether_type:'2048',data_hex:'',pad_bytes:String(e.pad_bytes),mac_bytes:String(e.mac_bytes),tag:tagged?{vid:'10',pcp:'7',dei:'1'}:null,fcs_hex:e.fcs_hex,mac_hex:e.header_hex+'00'.repeat(e.pad_bytes)+e.fcs_hex};}
function vlanFixture(){
 const source=vectorWire(true),untagged=vectorWire(false),frameId='g:0';
 const devices=[{id:'N.a',kind:'endpoint',mac:source.src_mac,multicast:[]},{id:'N.b',kind:'switch',mac:null,multicast:[{vid:'10',dst_mac:source.dst_mac,egresses:['N.b.tx_c']}],vlan_fdb:[],unknown_multicast:'drop'},{id:'N.c',kind:'endpoint',mac:'02:00:00:00:00:03',multicast:[{vid:'20',dst_mac:source.dst_mac}]},{id:'N.quiet',kind:'endpoint',mac:'02:00:00:00:00:04',multicast:[]}].map(d=>({...d,queue_capacity:'4'}));
 const directions=[['N.a.tx','N.b.rx_a'],['N.b.tx_a','N.a.rx'],['N.b.tx_c','N.c.rx'],['N.c.tx','N.b.rx_c'],['N.b.tx_quiet','N.quiet.rx'],['N.quiet.tx','N.b.rx_quiet']].map(([from_port,to_port])=>({from_port,to_port,bitrate_bps:'1000000000',delay_ps:'1000'}));
 const ports=[['N.a.tx','N.a.rx','10',true],['N.b.tx_a','N.b.rx_a','10',true],['N.b.tx_c','N.b.rx_c','10',false],['N.c.tx','N.c.rx','20',false],['N.b.tx_quiet','N.b.rx_quiet','10',false],['N.quiet.tx','N.quiet.rx','10',false]].map(([port,ingress,pvid,tagged])=>({port,ingress,pvid,admit:'all',default_priority:'2',vlans:[{vid:pvid,tagged}]}));
 const outputs=directions.map(d=>({port:d.from_port,scheduler:'strict_priority',queues:Array.from({length:8},(_,p)=>({priority:String(p),capacity_frames:'4',capacity_bytes:'256'}))}));
 const frame=record('frame',frameId,'N.a',frameId,0,{source:'N.a',...source,generated_ps:'0',ready_ps:'0',flow_id:'group',priority:'7',deadline_ps:'2000000',source_vlan_id:'10'});frame.schema_version=3;
 function transfer(from,to,parent,wire,queued,sof,eof,release,arrival){const r=record('transfer',`${frameId}@${from}`,from,frameId,release,{frame_id:frameId,parent_transfer_id:parent,from_port:from,to_port:to,queued_ps:String(queued),sof_ps:String(sof),eof_ps:String(eof),release_ps:String(release),arrival_ps:String(arrival),planned_eof_ps:String(eof),planned_release_ps:String(release),planned_arrival_ps:String(arrival),status:'serialized',drop_reason:null,queue_id:`${from}.queue.7`,priority:'7',vlan_id:'10',wire});r.schema_version=3;return r;}
 const incoming=transfer('N.a.tx','N.b.rx_a',null,source,0,0,608000,704000,609000),child=transfer('N.b.tx_c','N.c.rx',incoming.record_id,untagged,610000,620000,1196000,1292000,1197000);
 const rx=record('reception',`${incoming.record_id}@rx`,'N.b',frameId,610000,{frame_id:frameId,transfer_id:incoming.record_id,ingress:'N.b.rx_a',observed_ps:'609000',ready_ps:'610000',planned_ready_ps:'610000',status:'forwarded',reason:null,egress_transfer_ids:[child.record_id],vlan_id:'10',priority:'7'});rx.schema_version=2;
 const received=record('reception',`${child.record_id}@rx`,'N.c',frameId,1198000,{frame_id:frameId,transfer_id:child.record_id,ingress:'N.c.rx',observed_ps:'1197000',ready_ps:'1198000',planned_ready_ps:'1198000',status:'received',reason:null,egress_transfer_ids:[],vlan_id:'20',priority:'2'});received.schema_version=2;
 return {schema_version:2,metadata:{model_profile:'ethernet.l2.vlan.v1',model_schemas:[{schema_name:'ethernet.frame',schema_version:3},{schema_name:'ethernet.transfer',schema_version:3},{schema_name:'ethernet.reception',schema_version:2}],flows:[{flow_id:'group',priority:'7',deadline_ps:'2000000',dst_mac:source.dst_mac,tag:source.tag,source_vlan_id:'10'}],ethernet_topology:{devices,directions,ports,outputs}},simulation:{start_ps:'0',end_ps:'2000000',partial:false,termination:'events_exhausted',model_records:[frame,incoming,rx,child,received]}};
}
test('VLAN hop wire and classification preserve source contract and reclassify untagged ingress',()=>{const m=E.parseResults(vlanFixture());assert.equal(m.vlan,true);assert.equal(m.frames.get('g:0').source_vlan_id,'10');assert.equal(m.transfers.get('g:0@N.a.tx').wire.mac_bytes,'68');assert.equal(m.transfers.get('g:0@N.b.tx_c').wire.mac_bytes,'64');assert.equal(m.receptions.get('g:0@N.b.tx_c@rx').vlan_id,'20');assert.equal(m.receptions.get('g:0@N.b.tx_c@rx').priority,'2');assert.equal(m.policies.size,6);assert.equal(E.stateAt(m,610000n).classes.get('N.b.tx_c.queue.7').bytes,64n);assert.equal(E.stateAt(m,0n).classes.get('N.a.tx.queue.7').bytes,0n);});
test('VLAN display filter keeps global replay counts and supports hop VLAN separate from receive VLAN',()=>{const m=E.parseResults(vlanFixture()),before=E.stateAt(m,m.end);assert.equal(E.visibleTransfers(m,'10').length,2);assert.equal(E.visibleTransfers(m,'20').length,0);assert.equal(E.visibleTransfers(m,null).length,2);assert.deepEqual(E.stateAt(m,m.end),before);assert.equal(before.counts.received,1);const step=E.stepTransfers(m,609000n);E.stateAt(m,m.end);assert.deepEqual(E.stepTransfers(m,609000n),step);});
test('VLAN model rejects corrupt TCI, tag, FCS, length, mixed schema, class, reference and policy',()=>{for(const mutate of [
 r=>r.simulation.model_records[0].data.tag.vid='0',r=>r.simulation.model_records[0].data.tag.pcp='8',r=>r.simulation.model_records[0].data.tag.dei='2',r=>r.simulation.model_records[1].data.wire.mac_hex=r.simulation.model_records[1].data.wire.mac_hex.replace('8100f00a','8100e00a'),r=>r.simulation.model_records[3].data.wire.fcs_hex='00000000',r=>r.simulation.model_records[3].data.wire.mac_bytes='68',r=>r.simulation.model_records[3].schema_version=2,r=>r.metadata.model_schemas[0].schema_version=2,r=>r.simulation.model_records[3].data.priority='2',r=>r.simulation.model_records[4].data.priority='7',r=>r.simulation.model_records[4].data.vlan_id='10',r=>r.simulation.model_records[3].data.parent_transfer_id='missing',r=>r.metadata.ethernet_topology.ports.pop(),r=>r.metadata.ethernet_topology.ports[2].vlans[0].tagged=true,r=>r.metadata.ethernet_topology.devices[1].multicast[0].egresses=['N.a.tx'],r=>r.metadata.ethernet_topology.devices[2].multicast[0].vid='10',r=>r.metadata.flows[0].priority='6',r=>r.simulation.model_records[3].data.planned_eof_ps='1196001',r=>r.metadata.ethernet_topology.devices[1].vlan_fdb.push({vid:'10',dst_mac:'00:00:00:00:00:00',egress:'N.b.tx_c'})
 ]){const raw=vlanFixture();mutate(raw);assert.throws(()=>E.parseResults(raw),/Ethernet:/);}});
test('VLAN immediate endpoint filter keeps one reason without inventing a dropped copy',()=>{const raw=vlanFixture(),rx=raw.simulation.model_records[4];raw.metadata.ethernet_topology.devices[2].multicast=[];Object.assign(rx.data,{status:'filtered',reason:'multicast_not_subscribed',ready_ps:rx.data.observed_ps,planned_ready_ps:null});rx.time_ps=rx.data.observed_ps;const m=E.parseResults(raw),s=E.stateAt(m,m.end);assert.equal(s.counts.filtered,1);assert.equal(s.counts.dropped,0);assert.equal(s.counts.received,0);});
test('VLAN ingress admission rejection stops before child offers and requires exact classification',()=>{const raw=vlanFixture(),rx=raw.simulation.model_records[2];raw.metadata.ethernet_topology.ports[1].admit='untagged_only';Object.assign(rx.data,{status:'filtered',reason:'ingress_frame_type',ready_ps:rx.data.observed_ps,planned_ready_ps:null,egress_transfer_ids:[]});rx.time_ps=rx.data.observed_ps;raw.simulation.model_records.splice(3);const m=E.parseResults(raw);assert.equal(m.receptions.size,1);assert.equal(m.transfers.size,1);assert.equal(E.stateAt(m,m.end).counts.filtered,1);});
test('VLAN pending planned arrival never synthesizes receiver or classification',()=>{const raw=vlanFixture(),t=raw.simulation.model_records[1];raw.simulation.end_ps='609000';raw.simulation.termination='time_limit';t.data.arrival_ps=null;t.data.release_ps=null;t.time_ps='608000';raw.simulation.model_records.splice(2);const m=E.parseResults(raw);assert.equal(m.receptions.size,0);assert.equal(E.stateAt(m,m.end).counts.received,0);assert.equal(E.stepTransfers(m,m.end)[0].arrived,false);});
module.exports.vlanFixture=vlanFixture;
