// NODE_PATH=<playwright node_modules> node tests/network_viewer_browser.cjs <results.json> ...
// Uses current production assets directly so concurrent Rust edits cannot select stale assets.
'use strict';
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {pathToFileURL}=require('node:url');
const E=require('../crates/dir-simulator/src/tool/viewer/assets/ethernet-model.js');
const inputs=process.argv.slice(2),exportedHtml=inputs[0]==='--exported-html';if(exportedHtml)inputs.shift();if(!inputs.length||(exportedHtml&&inputs.length%2))throw new Error('Pass results.json files, or --exported-html followed by results.json / exported.html pairs');const cases=exportedHtml?Array.from({length:inputs.length/2},(_,i)=>({result:inputs[i*2],html:inputs[i*2+1]})):inputs.map(result=>({result}));
const assets=path.resolve(__dirname,'../crates/dir-simulator/src/tool/viewer/assets'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'dir-network-browser-'));
function render(raw){let html=fs.readFileSync(path.join(assets,'index.html'),'utf8');html=html.replace('<link rel="stylesheet" href="style.css">',`<style>${fs.readFileSync(path.join(assets,'style.css'),'utf8').replace(/<\/style/gi,'<\\/style')}</style>`);html=html.replace('<script src="model.js"></script>',`<script id="embedded-results" type="application/json">${JSON.stringify(raw).replaceAll('<','\\u003c')}</script><script src="model.js"></script>`);for(const name of ['model','ethernet-model','ethernet-app','transaction-model','transaction-app','app'])html=html.replace(`<script src="${name}.js"></script>`,`<script>${fs.readFileSync(path.join(assets,`${name}.js`),'utf8').replace(/<\/script/gi,'<\\/script')}</script>`);return html;}
(async()=>{let browser;try{
 browser=await chromium.launch({headless:true});for(let i=0;i<cases.length;i++){
  const raw=JSON.parse(fs.readFileSync(cases[i].result,'utf8')),m=E.parseResults(raw),html=cases[i].html?path.resolve(cases[i].html):path.join(temp,`${i}.html`);if(!cases[i].html)fs.writeFileSync(html,render(raw));
  const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith('file:'))requests.push(r.url());});await page.goto(pathToFileURL(html).href);await page.locator('#ethernet-dashboard').waitFor({state:'visible'});
  assert.equal(await page.locator('#error-banner').isVisible(),false);assert.equal(await page.locator('#eth-network [data-device]').count(),m.devices.size);assert.equal(await page.locator('#eth-network [data-direction]').count(),m.directions.size);
  if(m.composite){assert(await page.locator('#eth-composite-panel').isVisible());assert.equal(await page.locator('#eth-network [data-can-node]').count(),m.canModel.nodes.length);assert.equal(await page.locator('#eth-network [data-can-bus-node]').count(),m.canModel.buses.length);assert.equal(await page.locator('#eth-network [data-can-direction]').count(),m.canModel.controllers.length*2);if(m.canModel.requests.length){await page.locator('[data-can-request]').first().click();assert((await page.locator('#eth-details').innerText()).includes('CAN'));}const origin=[...m.origins.keys()][0];if(origin){await page.locator('#eth-origin-filter').selectOption(origin);assert.equal(await page.locator('#eth-rows tr').count(),Math.min(500,[...m.transfers.values()].filter(t=>(m.originByRecord.get('ethernet/'+t.frame_id)??t.frame_id)===origin).length));await page.locator('#eth-origin-filter').selectOption('');}
   for(const origin of m.origins.keys()){await page.locator('#eth-origin-filter').selectOption(origin);assert.equal(await page.locator('#eth-can-state [data-can-request]').count(),m.canModel.requests.filter(r=>m.originByRecord.get('can/'+r.id)===origin).length);assert.equal(await page.locator('#eth-frames [data-frame]').count(),Math.min(500,[...m.frames.values()].filter(f=>m.originByRecord.get('ethernet/'+f.id)===origin).length));}await page.locator('#eth-origin-filter').selectOption('');
   for(const request of m.canModel.requests.filter(r=>m.frames.has(r.id))){await page.locator('[data-frame='+JSON.stringify(request.id)+']').click();assert((await page.locator('#eth-details').innerText()).includes('Source FCS'));assert((await page.locator('#eth-details').innerText()).includes(m.originByRecord.get('ethernet/'+request.id)));await page.locator('[data-can-request='+JSON.stringify(request.id)+']').click();assert((await page.locator('#eth-details').innerText()).includes('\"medium\": \"CAN\"'));}
  }
  if(m.dynamic){assert(await page.locator('#eth-policy-panel').isVisible());assert((await page.locator('#eth-policy-state').innerText()).includes('Policy epoch'));assert.equal(await page.locator('#eth-policy-state [data-policy-port]').count(),m.directions.size);}
  if(m.tsn){assert(await page.locator('#eth-tsn-panel').isVisible());assert.equal(await page.locator('#eth-tsn-state [data-tsn-port]').count(),m.directions.size);}
  if(m.transfers.size){await page.locator('#eth-rows tr').first().click();assert((await page.locator('#eth-details').innerText()).includes('FCS'));if(m.dynamic)assert((await page.locator('#eth-details').innerText()).includes('Offer policy epoch'));}
  await page.locator('#eth-jump-value').fill(m.end.toString());await page.locator('#eth-jump').click();assert((await page.locator('#eth-time').innerText()).includes(`${m.end} ps`));
  if(m.eventTimes.length>2){await page.locator('#eth-prev').click();const destination=await page.locator('#eth-time').innerText(),policy=m.dynamic?await page.locator('#eth-policy-state').innerText():null,movement=await page.locator('#eth-network circle[data-transfer]').evaluateAll(nodes=>nodes.map(n=>n.dataset.transfer));await page.locator('#eth-next').click();await page.locator('#eth-prev').click();assert.equal(await page.locator('#eth-time').innerText(),destination);if(m.dynamic)assert.equal(await page.locator('#eth-policy-state').innerText(),policy);assert.deepEqual(await page.locator('#eth-network circle[data-transfer]').evaluateAll(nodes=>nodes.map(n=>n.dataset.transfer)),movement);}
  await page.locator('#eth-play').click();await page.waitForTimeout(80);assert.equal(await page.locator('#eth-network circle[data-transfer]').count(),0);await page.locator('#eth-play').click();
  await page.setViewportSize({width:390,height:850});assert(await page.locator('#eth-network').isVisible());assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);await page.close();console.log('Network browser passed:',cases[i].result,...(cases[i].html?['exported HTML:',html]:[]));
 }
}finally{if(browser)await browser.close();fs.rmSync(temp,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1;});
