"""Validate the canonical hierarchy data and render its standalone HTML annex."""

from __future__ import annotations

import html
import re
from pathlib import Path
from urllib.parse import quote

from check_traceability import obj

SOURCE = Path("docs/要件階層.json")
OUTPUT = Path("docs/要件階層.html")
IDENTIFIER = re.compile(r"DIR-REQ-\d{4}")


def load(check) -> list[dict]:
    """Require one recorded parent (or explicit root) for every active ID."""
    try:
        data = obj((check.root / SOURCE).read_text(encoding="utf-8"))
    except (OSError, UnicodeError, ValueError) as error:
        raise ValueError(f"{SOURCE}: {error}") from error
    if (not isinstance(data, dict) or set(data) != {"schema_version", "requirements"}
            or type(data["schema_version"]) is not int or data["schema_version"] != 1
            or not isinstance(data["requirements"], list)):
        raise ValueError(f"{SOURCE}: invalid hierarchy schema")
    rows = data["requirements"]
    parents = {}
    for row in rows:
        if not isinstance(row, dict) or set(row) != {"id", "parent", "position", "decomposition"}:
            raise ValueError(f"{SOURCE}: invalid hierarchy row")
        ident, parent = row["id"], row["parent"]
        if not isinstance(ident, str) or not IDENTIFIER.fullmatch(ident):
            raise ValueError(f"{SOURCE}: invalid requirement ID {ident!r}")
        if ident in parents:
            raise ValueError(f"{SOURCE}: duplicate requirement {ident}")
        if parent is not None and (not isinstance(parent, str) or not IDENTIFIER.fullmatch(parent)):
            raise ValueError(f"{SOURCE}: {ident}: invalid parent {parent!r}")
        for field in ("position", "decomposition"):
            if not isinstance(row[field], str) or not row[field].strip():
                raise ValueError(f"{SOURCE}: {ident}: invalid {field}")
        parents[ident] = parent
    missing = check.requirements - parents.keys()
    extra = parents.keys() - check.requirements
    if missing or extra:
        raise ValueError(f"{SOURCE}: hierarchy coverage mismatch; missing={sorted(missing)}, unknown={sorted(extra)}")
    for ident, parent in parents.items():
        if parent is not None and parent not in parents:
            raise ValueError(f"{SOURCE}: {ident}: unknown parent {parent}")
    # Iterative traversal also handles deeply nested future hierarchies.
    complete = set()
    for ident in parents:
        path = set()
        current = ident
        while current is not None and current not in complete:
            if current in path:
                raise ValueError(f"{SOURCE}: hierarchy cycle at {current}")
            path.add(current)
            current = parents[current]
        complete.update(path)
    return rows


def render(check, rows: list[dict], css: str) -> str:
    esc = html.escape
    requirement_path = quote("要件定義書.md")
    body = []
    for row in rows:
        ident, parent = row["id"], row["parent"]
        link = f'<a class="trace-id" href="{requirement_path}#{ident.lower()}">{ident}</a>'
        parent_link = (f'<a class="trace-id" href="#{parent.lower()}">{parent}</a>'
                       if parent else "—（根）")
        body.append(
            f'<tr id="{ident.lower()}"><td>{link}</td>'
            f'<td>{esc(check.req_titles.get(ident, ""))}</td><td>{parent_link}</td>'
            f'<td>{esc(row["position"])}</td><td>{esc(row["decomposition"])}</td></tr>'
        )
    roots = sum(row["parent"] is None for row in rows)
    return "\n".join([
        "<!doctype html>",
        "<!-- Generated by scripts/generate_traceability.py. Do not edit manually. -->",
        '<html lang="ja"><head><meta charset="utf-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        '<title>要件階層</title>', f'<style>\n{css}\n</style>',
        '</head><body><header><h1>要件階層</h1>',
        '<p>要件定義書の別紙。各有効要件の主親、階層上の位置、分解状態を示します。</p></header>',
        f'<p class="report-link"><a href="{requirement_path}">要件定義書</a> ／ '
        '<a href="要件トレーサビリティ一覧.html">要件トレーサビリティ一覧</a></p>',
        '<p>主親と分解状態の正本は<a href="要件階層.json">要件階層.json</a>です。'
        '要件名は要件定義書から取得し、scripts/generate_traceability.pyで生成します。</p>',
        '<p>各有効要件は主親一件または根として登録します。関連する横断条件は要件定義書第1.1節と'
        '各要件の注釈に従います。分解状態は責務の整理状況を表し、子の存在は仕様確定や試験合格の証拠とは区別します。</p>',
        f'<p>有効要件：{len(rows)}件 ／ 根：{roots}件。要件IDから本文、主親IDから本表の親行へ移動できます。</p>',
        '<div class="table-scroll"><table><caption>要件ごとの主親と分解状態</caption>',
        '<thead><tr><th scope="col">要件ID</th><th scope="col">要件名</th>'
        '<th scope="col">主親ID</th><th scope="col">階層上の位置</th>'
        '<th scope="col">分解状態</th></tr></thead><tbody>',
        *body, '</tbody></table></div></body></html>', '',
    ])
